# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.11.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.11.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jameshenson/Noriaela

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jameshenson/Noriaela

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.11.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.11.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jameshenson/Noriaela/CMakeFiles /Users/jameshenson/Noriaela/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jameshenson/Noriaela/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Noriaela

# Build rule for target.
Noriaela: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Noriaela
.PHONY : Noriaela

# fast build rule for target.
Noriaela/fast:
	$(MAKE) -f CMakeFiles/Noriaela.dir/build.make CMakeFiles/Noriaela.dir/build
.PHONY : Noriaela/fast

Hacks/skinchanger.o: Hacks/skinchanger.cpp.o

.PHONY : Hacks/skinchanger.o

# target to build an object file
Hacks/skinchanger.cpp.o:
	$(MAKE) -f CMakeFiles/Noriaela.dir/build.make CMakeFiles/Noriaela.dir/Hacks/skinchanger.cpp.o
.PHONY : Hacks/skinchanger.cpp.o

Hacks/skinchanger.i: Hacks/skinchanger.cpp.i

.PHONY : Hacks/skinchanger.i

# target to preprocess a source file
Hacks/skinchanger.cpp.i:
	$(MAKE) -f CMakeFiles/Noriaela.dir/build.make CMakeFiles/Noriaela.dir/Hacks/skinchanger.cpp.i
.PHONY : Hacks/skinchanger.cpp.i

Hacks/skinchanger.s: Hacks/skinchanger.cpp.s

.PHONY : Hacks/skinchanger.s

# target to generate assembly for a file
Hacks/skinchanger.cpp.s:
	$(MAKE) -f CMakeFiles/Noriaela.dir/build.make CMakeFiles/Noriaela.dir/Hacks/skinchanger.cpp.s
.PHONY : Hacks/skinchanger.cpp.s

Hooks/firegameevent.o: Hooks/firegameevent.cpp.o

.PHONY : Hooks/firegameevent.o

# target to build an object file
Hooks/firegameevent.cpp.o:
	$(MAKE) -f CMakeFiles/Noriaela.dir/build.make CMakeFiles/Noriaela.dir/Hooks/firegameevent.cpp.o
.PHONY : Hooks/firegameevent.cpp.o

Hooks/firegameevent.i: Hooks/firegameevent.cpp.i

.PHONY : Hooks/firegameevent.i

# target to preprocess a source file
Hooks/firegameevent.cpp.i:
	$(MAKE) -f CMakeFiles/Noriaela.dir/build.make CMakeFiles/Noriaela.dir/Hooks/firegameevent.cpp.i
.PHONY : Hooks/firegameevent.cpp.i

Hooks/firegameevent.s: Hooks/firegameevent.cpp.s

.PHONY : Hooks/firegameevent.s

# target to generate assembly for a file
Hooks/firegameevent.cpp.s:
	$(MAKE) -f CMakeFiles/Noriaela.dir/build.make CMakeFiles/Noriaela.dir/Hooks/firegameevent.cpp.s
.PHONY : Hooks/firegameevent.cpp.s

Hooks/framestage.o: Hooks/framestage.cpp.o

.PHONY : Hooks/framestage.o

# target to build an object file
Hooks/framestage.cpp.o:
	$(MAKE) -f CMakeFiles/Noriaela.dir/build.make CMakeFiles/Noriaela.dir/Hooks/framestage.cpp.o
.PHONY : Hooks/framestage.cpp.o

Hooks/framestage.i: Hooks/framestage.cpp.i

.PHONY : Hooks/framestage.i

# target to preprocess a source file
Hooks/framestage.cpp.i:
	$(MAKE) -f CMakeFiles/Noriaela.dir/build.make CMakeFiles/Noriaela.dir/Hooks/framestage.cpp.i
.PHONY : Hooks/framestage.cpp.i

Hooks/framestage.s: Hooks/framestage.cpp.s

.PHONY : Hooks/framestage.s

# target to generate assembly for a file
Hooks/framestage.cpp.s:
	$(MAKE) -f CMakeFiles/Noriaela.dir/build.make CMakeFiles/Noriaela.dir/Hooks/framestage.cpp.s
.PHONY : Hooks/framestage.cpp.s

Interfaces/Hooks.o: Interfaces/Hooks.cpp.o

.PHONY : Interfaces/Hooks.o

# target to build an object file
Interfaces/Hooks.cpp.o:
	$(MAKE) -f CMakeFiles/Noriaela.dir/build.make CMakeFiles/Noriaela.dir/Interfaces/Hooks.cpp.o
.PHONY : Interfaces/Hooks.cpp.o

Interfaces/Hooks.i: Interfaces/Hooks.cpp.i

.PHONY : Interfaces/Hooks.i

# target to preprocess a source file
Interfaces/Hooks.cpp.i:
	$(MAKE) -f CMakeFiles/Noriaela.dir/build.make CMakeFiles/Noriaela.dir/Interfaces/Hooks.cpp.i
.PHONY : Interfaces/Hooks.cpp.i

Interfaces/Hooks.s: Interfaces/Hooks.cpp.s

.PHONY : Interfaces/Hooks.s

# target to generate assembly for a file
Interfaces/Hooks.cpp.s:
	$(MAKE) -f CMakeFiles/Noriaela.dir/build.make CMakeFiles/Noriaela.dir/Interfaces/Hooks.cpp.s
.PHONY : Interfaces/Hooks.cpp.s

Interfaces/interfaces.o: Interfaces/interfaces.cpp.o

.PHONY : Interfaces/interfaces.o

# target to build an object file
Interfaces/interfaces.cpp.o:
	$(MAKE) -f CMakeFiles/Noriaela.dir/build.make CMakeFiles/Noriaela.dir/Interfaces/interfaces.cpp.o
.PHONY : Interfaces/interfaces.cpp.o

Interfaces/interfaces.i: Interfaces/interfaces.cpp.i

.PHONY : Interfaces/interfaces.i

# target to preprocess a source file
Interfaces/interfaces.cpp.i:
	$(MAKE) -f CMakeFiles/Noriaela.dir/build.make CMakeFiles/Noriaela.dir/Interfaces/interfaces.cpp.i
.PHONY : Interfaces/interfaces.cpp.i

Interfaces/interfaces.s: Interfaces/interfaces.cpp.s

.PHONY : Interfaces/interfaces.s

# target to generate assembly for a file
Interfaces/interfaces.cpp.s:
	$(MAKE) -f CMakeFiles/Noriaela.dir/build.make CMakeFiles/Noriaela.dir/Interfaces/interfaces.cpp.s
.PHONY : Interfaces/interfaces.cpp.s

SDK/netvarmanager.o: SDK/netvarmanager.cpp.o

.PHONY : SDK/netvarmanager.o

# target to build an object file
SDK/netvarmanager.cpp.o:
	$(MAKE) -f CMakeFiles/Noriaela.dir/build.make CMakeFiles/Noriaela.dir/SDK/netvarmanager.cpp.o
.PHONY : SDK/netvarmanager.cpp.o

SDK/netvarmanager.i: SDK/netvarmanager.cpp.i

.PHONY : SDK/netvarmanager.i

# target to preprocess a source file
SDK/netvarmanager.cpp.i:
	$(MAKE) -f CMakeFiles/Noriaela.dir/build.make CMakeFiles/Noriaela.dir/SDK/netvarmanager.cpp.i
.PHONY : SDK/netvarmanager.cpp.i

SDK/netvarmanager.s: SDK/netvarmanager.cpp.s

.PHONY : SDK/netvarmanager.s

# target to generate assembly for a file
SDK/netvarmanager.cpp.s:
	$(MAKE) -f CMakeFiles/Noriaela.dir/build.make CMakeFiles/Noriaela.dir/SDK/netvarmanager.cpp.s
.PHONY : SDK/netvarmanager.cpp.s

SDK/offsets.o: SDK/offsets.cpp.o

.PHONY : SDK/offsets.o

# target to build an object file
SDK/offsets.cpp.o:
	$(MAKE) -f CMakeFiles/Noriaela.dir/build.make CMakeFiles/Noriaela.dir/SDK/offsets.cpp.o
.PHONY : SDK/offsets.cpp.o

SDK/offsets.i: SDK/offsets.cpp.i

.PHONY : SDK/offsets.i

# target to preprocess a source file
SDK/offsets.cpp.i:
	$(MAKE) -f CMakeFiles/Noriaela.dir/build.make CMakeFiles/Noriaela.dir/SDK/offsets.cpp.i
.PHONY : SDK/offsets.cpp.i

SDK/offsets.s: SDK/offsets.cpp.s

.PHONY : SDK/offsets.s

# target to generate assembly for a file
SDK/offsets.cpp.s:
	$(MAKE) -f CMakeFiles/Noriaela.dir/build.make CMakeFiles/Noriaela.dir/SDK/offsets.cpp.s
.PHONY : SDK/offsets.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Noriaela.dir/build.make CMakeFiles/Noriaela.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Noriaela.dir/build.make CMakeFiles/Noriaela.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Noriaela.dir/build.make CMakeFiles/Noriaela.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Noriaela"
	@echo "... Hacks/skinchanger.o"
	@echo "... Hacks/skinchanger.i"
	@echo "... Hacks/skinchanger.s"
	@echo "... Hooks/firegameevent.o"
	@echo "... Hooks/firegameevent.i"
	@echo "... Hooks/firegameevent.s"
	@echo "... Hooks/framestage.o"
	@echo "... Hooks/framestage.i"
	@echo "... Hooks/framestage.s"
	@echo "... Interfaces/Hooks.o"
	@echo "... Interfaces/Hooks.i"
	@echo "... Interfaces/Hooks.s"
	@echo "... Interfaces/interfaces.o"
	@echo "... Interfaces/interfaces.i"
	@echo "... Interfaces/interfaces.s"
	@echo "... SDK/netvarmanager.o"
	@echo "... SDK/netvarmanager.i"
	@echo "... SDK/netvarmanager.s"
	@echo "... SDK/offsets.o"
	@echo "... SDK/offsets.i"
	@echo "... SDK/offsets.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

